name: PR Label Checker
description: This GitHub Action checks if labels are attached to a PR and fails if any of configured listed labels are not present.
branding:
  icon: 'check-circle'
  color: 'green'

on:
  pull_request:
    branches: 
    - development
    types: [ labeled, opened, unlabeled ]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Labels added
      if: ${{ contains(fromJson('["bug", "documentation", "enhancement"]'), github.event.label.name) == true }}
      run: echo Pass
    - name: Labels not added (bug, documentation, or enhancement)
      if: ${{ contains(fromJson('["bug"]'), github.event.label.name) != true }}
      run: exit 1
      
